WIP: Search for illegal root logins

diff --git a/Betreibssysteme I/Beleg/s77096 b/Betreibssysteme I/Beleg/s77096
--- a/Betreibssysteme I/Beleg/s77096
+++ b/Betreibssysteme I/Beleg/s77096
@@ -3,8 +3,11 @@
 URL="http://ilpro122.informatik.htw-dresden.de/logs/"
 MODE=0
 
-ARGS1="ipo51 ipc88 ilpro122 fohls all"
-ARGS2="root users login"
+HOSTS="ipo51 ipc88 ilpro122 fohls all"
+USERS="root users login"
+
+# TMPDIR="$(mktemp -d)"
+TMPDIR="/tmp/tmp.Uvsdr5RgCu"
 
 function usage {
     echo
@@ -27,39 +30,71 @@ function validate_ip {
     return $stat;
 }
 
+function cleanup {
+    # rm -Rf $TMPDIR
+    echo "Fake cleanup"
+}
+
 function error {
+    cleanup
     echo -e "\e[31m$1\e[39m"
+    exit 1
 }
 
 if [ "$#" -ne 1 ] && [ "$#" -ne 2 ]; then
-    error "Illegal number of arguments"
     usage
-    exit 1
+    error "Illegal number of arguments"
 fi
 
 if [ "$#" == 1 ]; then
-    validate_ip $1 || (error "Malformed IP address"; exit 1)
+    validate_ip $1 || (usage; error "Malformed IP address")
+
+    IP="$1"
 fi
 
 if [ "$#" == 2 ]; then
     MODE=1
 
-    if [[ ! $ARGS1 == *"$1"* ]]; then
-        error "Illegal first argument"
+    if [[ ! $HOSTS == *"$1"* ]]; then
         usage
-        exit 1
+        error "Illegal first argument"
     fi
 
-    if [[ ! $ARGS2 == *"$2"* ]]; then
-        error "Illegal second argument"
+    if [[ ! $USERS == *"$2"* ]]; then
         usage
-        exit 1
+        error "Illegal second argument"
     fi
+
+    HOST="$1"
+    USER="$2"
 fi
 
-TMPDIR="$(mktemp -d)"
-wget -rq --no-parent -A "*.log*" -p $TMPDIR $URL
-ls -lah $TMPDIR
+echo "Downloading logs from $URL to $TMPDIR"
 
-# rm -Rf "$TMPDIR"
+# Download log files
+#  -rq          recursive and quiet
+#  -nH          create no host directory
+#  -A           accept list: accept only log files
+#  -P           prefix: download to temp folder
+#  --cut-dirs   omit root directory
+# wget -rq -nH -A "*.log*" -P $TMPDIR --cut-dirs=1 $URL || error "Unable to download log files. Abort."
+
+echo "Successfully downloaded log files"
+echo "Decompress rotated log files"
+
+# Find and uncompress all gz files
+find $TMPDIR -type f -name "*.gz" -exec gzip -d "{}" \;
+
+if [ $MODE -eq 1 ]; then
+    if [ $HOST == "all" ]; then
+        HOST="auth"
+    fi
+
+    FILES="$(find $TMPDIR -type f -name "*$HOST*")"
+fi
+
+cat $FILES | grep "Failed password for root" | awk '{print $11}' | sort -V | uniq -c # Sort by IP (version number) https://www.madboa.com/geek/sort-addr/
+cat $FILES | grep "Failed password for root" | awk '{print $11}' | uniq -c | sort -n # Sort by appereance (version number)
+
+cleanup
 exit 0
